[app]
title = Alien Invasion
package.name = alieninvasion
package.domain = org.manuel

source.dir = .
source.include_exts = py,json

version = 1.0

# SDL2 bootstrap is required for pygame apps
p4a.bootstrap = sdl2

# No version pinning — let p4a use its bundled recipes
requirements = python3,pygame

orientation = landscape

# Android target
android.api = 33
android.minapi = 21

android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,VIBRATE

android.accept_sdk_license = True

android.archs = arm64-v8a

# Fullscreen — no title bar
fullscreen = 1

# Release signing — JKS keystore generated by CI workflow
android.keystore = release.jks
android.keystore_password = AlienInvasion2024!
android.keyalias = alieninvasion
android.keyalias_password = AlienInvasion2024!

[buildozer]
log_level = 2
warn_on_root = 1
